name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Erlang/OTP + Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '27.0'
          elixir-version: '1.17.3'

      - name: Install Dependencies
        run: mix deps.get

      - name: Format Check
        run: mix format --check-formatted

  test:
    name: Test with OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      fail-fast: false
      matrix:
        otp: ['26.2', '27.0', '28.0']
        elixir: ['1.17.3', '1.18.4', '1.19.3']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Setup Erlang/OTP + Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}

    - name: Install Dependencies
      run: mix deps.get

    - name: Run Tests
      run: mix test

  docs:
    name: Documentations
    runs-on: ubuntu-latest
    needs: [format, test]
    steps:
      - uses: actions/checkout@v6

      - name: Setup Erlang/OTP + Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '27.0'
          elixir-version: '1.17.3'

      - name: Install Dependencies
        run: mix deps.get

      - name: Generate Docs
        run: mix docs
